### ISSUE TITLE
Error while using yarn since 'monorepo structure'

### ISSUE THREAD

**Issue by Kllngii** [r6db/app#23]
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@r6db%2fconstants: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/lasse_kelling/git/R6DBApp/packages/desktop/yarn-error.log".
```
The yarn-error.log file:
```
Arguments: 
  /usr/local/Cellar/node@8/8.12.0/bin/node /usr/local/Cellar/yarn/1.10.1/libexec/bin/yarn.js

PATH: 
  /usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/opt/gettext/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

Yarn version: 
  1.10.1

Node version: 
  8.12.0

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/@r6db%2fconstants: Not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:61073:18)
      at Request.self.callback (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:120166:22)
      at emitTwo (events.js:126:13)
      at Request.emit (events.js:214:7)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:121138:10)
      at emitOne (events.js:116:13)
      at Request.emit (events.js:211:7)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:121060:12)
      at Object.onceWrapper (events.js:313:30)
      at emitNone (events.js:111:20)
```
And then about 10.000 lines of dependency information

**Comment by LaxisB** [comment]
i updated the readme to show the new build instructions. 
it's not too complete yet, as the packages are not as coupled any more

**Comment by Kllngii** [comment]
Thanks, maybe it would be a great idea to use [TypeDoc](https://www.npmjs.com/package/typedoc) in addition to a good README.md. Maybe even with the addon [TypeDoc-Markdown](https://www.npmjs.com/package/typedoc-plugin-markdown) to create a good structure inside of a Markdown file.

**Comment by LaxisB** [comment]
i'm not quite sure what kinds of docu we want/need yet.  

what i thought of using:  
  
- website for user-facing stuff (landing page, guides, explanations, etc)
- github wiki for dev-facing stuff (architecture, reasoning for certian choices, etc)
- in-code comments and readmes (small stuff)

i don't see the value added from typedoc here, since api docu is also available in the editor from the declaration files. In theory, it could give a good overview on for a package consumer, but for what complexity cost? 
also, the times i used typedoc it was iffy at best, and non-funcitonal the rest of the time  
  
i'm happy to be taught wrong though

**Comment by Kllngii** [comment]
I think you are right, but I'm not yet familiar with Github-Wiki is it good enough, to display important things while coding?

**Comment by LaxisB** [comment]
while coding, you still have intellisense from the typescript.  
  
tsdoc just extracts that info into a website.  
gh wiki displays whatever you write.  
so most of the technical api would be in code, with the prose-style docs in the wiki
